In [694]:
%pip install MiniSom

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [695]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [696]:
dataset = pd.read_csv('preprocessed_data.csv')
X = dataset.iloc[:, :-1].values 
y = dataset.iloc[:, -1].values

In [697]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0,1))
X = sc.fit_transform(X)

In [698]:
from minisom import MiniSom
som = MiniSom(x=10, y=10, input_len= 15, sigma= 1.0, learning_rate = 0.5)
som.random_weights_init(X)
som.train_random(data = X, num_iteration = 100)

In [699]:
mappings = som.win_map(X)
preds = np.concatenate((mappings[(0,2)], mappings[(4,1)]), axis = 0)
preds = sc.inverse_transform(preds)

In [700]:
print('The suitable cities to live')
for i in preds[:, 0]:
  print(int(i))

The suitable cities to live
10273
10506
10507
10511
10525
11252
11289
11291
11292
11293
11295
11296
11297
11298
11303
11304
11321
11323
11324
11365
11376
11654
11666
11679
11687
11694
11702
12005
12015
12029
12030
12032
12033
12058
12066
12081
12089
15055
15065
15067
15308
15316
15317
15326
15327
15334
15340
15341
15349
15370
15371
15372
15373
15374
15382
15383
15399
15426
15427
15427
15428
15430
15431
15432
15433
15434
15436
15439
15443
15456
15459
15460
15461
15462
15463
15463
15464
15466
15467
15469
15472
15473
15474
15475
15475
15476
15478
15479
15556
15559
15559
15590
15591
15593
15594
15595
15595
15602
15603
15604
15786
15787
15797
15798
15799
15799
15806
15807
15808
15812
15815
15828
15831
15832
16179
16180
16181
16188
16192
16193
16195
16195
16198
16199
16200
16211


In [701]:
lst = ['Hyderabad', 'Delhi', 'Visakhapatnam', 'Amaravati', 'Amritsar',
'Kolkata', 'Chandigarh', 'Patna', 'Gurugram']

In [702]:
x = dataset.iloc[:,:-1]

In [703]:
int(preds[:, 0][0])

10273

In [704]:
d = dataset.loc[dataset['Number'] == int(preds[:, 0][0])]

In [705]:
d

Number  City   PM2.5    PM10     NO    NO2     NOx     NH3     CO   SO2  \
1603   10273     1  193.96  412.46  81.47  53.81  107.76  137.27  11.73  9.36   

         O3  Benzene  Toluene  Xylene  AQI  AQI_Bucket  
1603  34.22     9.01    17.88   14.17  377           4

In [706]:
p = []
for i in preds[:, 0]:
  p.append([int(i)])

In [707]:
p

[[10273],
 [10506],
 [10507],
 [10511],
 [10525],
 [11252],
 [11289],
 [11291],
 [11292],
 [11293],
 [11295],
 [11296],
 [11297],
 [11298],
 [11303],
 [11304],
 [11321],
 [11323],
 [11324],
 [11365],
 [11376],
 [11654],
 [11666],
 [11679],
 [11687],
 [11694],
 [11702],
 [12005],
 [12015],
 [12029],
 [12030],
 [12032],
 [12033],
 [12058],
 [12066],
 [12081],
 [12089],
 [15055],
 [15065],
 [15067],
 [15308],
 [15316],
 [15317],
 [15326],
 [15327],
 [15334],
 [15340],
 [15341],
 [15349],
 [15370],
 [15371],
 [15372],
 [15373],
 [15374],
 [15382],
 [15383],
 [15399],
 [15426],
 [15427],
 [15427],
 [15428],
 [15430],
 [15431],
 [15432],
 [15433],
 [15434],
 [15436],
 [15439],
 [15443],
 [15456],
 [15459],
 [15460],
 [15461],
 [15462],
 [15463],
 [15463],
 [15464],
 [15466],
 [15467],
 [15469],
 [15472],
 [15473],
 [15474],
 [15475],
 [15475],
 [15476],
 [15478],
 [15479],
 [15556],
 [15559],
 [15559],
 [15590],
 [15591],
 [15593],
 [15594],
 [15595],
 [15595],
 [15602],
 [15603],
 [15604],


In [708]:
"""
import csv
header = ['ids']
file = open('predictions_som.csv', 'w+', newline ='') 
with file:     
    write = csv.writer(file) 
    write.writerow(header)
    write.writerows(p) """

"\nimport csv\nheader = ['ids']\nfile = open('predictions_som.csv', 'w+', newline ='') \nwith file:     \n    write = csv.writer(file) \n    write.writerow(header)\n    write.writerows(p) "

In [709]:
xyz=[]
for i in range(0,len(p)):
    d = dataset.loc[dataset['Number'] == int(p[i][0])]
    xyz.append(d["City"].values)

In [710]:
xyz

[array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], 

In [711]:
l = []
for i in range(len(p)):
    print(i)
    l.append(lst[xyz[i][0]])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125


In [712]:
newl = []
for i in l:
    if i in newl:
        pass
    else:
        newl.append(i)

In [713]:
newl

['Delhi', 'Hyderabad']